name: Build (Android)

on: [push, pull_request]

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: fna-net-patch-sdl2

      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r21e

      - name: Create folders
        run: mkdir -p out/x86_64 out/arm64-v8a && ls -l .

      - name: Configure CMake (arm64)
        run: cmake -B build -DCMAKE_TOOLCHAIN_FILE=$(dirname $(which ndk-build))/build/cmake/android.toolchain.cmake -DANDROID_ABI=arm64-v8a
      - name: Build (arm64)
        run: cmake --build build/ --config Release && cp build/*.so out/arm64-v8a/

      - name: Configure CMake (x86_64)
        run: cmake -B build -DCMAKE_TOOLCHAIN_FILE=$(dirname $(which ndk-build))/build/cmake/android.toolchain.cmake -DANDROID_ABI=x86_64
      - name: Build (x86_64)
        run: cmake --build build/ --clean-first --config Release && cp build/*.so out/x86_64/

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }} Artifacts (Android)
          path: out/
