name: Build (UWP)

on: [push, pull_request]

jobs:
  Build:
    name: UWP
    runs-on: windows-latest

    defaults:
      run:
        shell: pwsh

    steps:
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: fna-net-patch-uwp

      - name: Build
        run: msbuild visualc-winrt/libtheorafile.sln /p:BuildInParallel=true /p:configuration=release /p:platform=x64 /p:WindowsTargetPlatformVersion=10.0.17763.0

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }} Artifacts UWP x64
          path: |
            visualc-winrt/x64/Release/libtheorafile/*.dll
            visualc-winrt/x64/Release/libtheorafile/*.pri
